---

name: release
on:
  push:
    tags:
      - "v*"

jobs:
  pypi_release:
    name: "pypi_release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: release
        shell: bash
        run: ./entrypoint pypi_release
        env:
          SECRET_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  github_release:
    name: "github_release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: release
        shell: bash
        run: ./entrypoint github_release
        env:
          SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
